language: ruby

dist: trusty
sudo: false

cache: bundler

services:
  - mongodb

rvm:
  - 2.3.3
  - 2.5.0
  - jruby-9.1.13.0

bundler_args: --without tools

env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE='true'

before_install:
  # NOTE: https://github.com/travis-ci/travis-ci/issues/8978
  - gem update --system

after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
